### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by root9464** [hauph/pixi-react-chrome-dinosaur#1]
Hello, your code helped me a lot, but I would like to make a couple of changes, namely to replace the current elements with my own (for the place of the dinosaur - robot, for the place of cacti - Christmas trees, etc.) please tell me how can I do this? Because I didn't find any other pictures in your code, but only 1 with all the elements...

**Comment by hauph** [comment]
Hi, thank you for reaching out.
This project was developed using PixiJS, in which all elements (characters, objects etc) are usually stored in 1 sprite image file, and when I needed to show anything, I would crop that specific item out of the sprite image using PixiJS's `BaseTexture`.
Therefore if you want to replace your images, you need to provide them as a general sprite image.

**Comment by root9464** [comment]
Okay, well, I understood the animations of the dinosaur running how are they arranged? it's just that I saw some json files with incomprehensible contents in public

**Comment by root9464** [comment]
or is it enough for me to make a sprite.png and everything will change?

**Comment by hauph** [comment]
to create the animations of a moving object, you need to use this tool https://www.codeandweb.com/free-sprite-sheet-packer, it will create a `png` and `json` file corresponding to that action.

**Comment by root9464** [comment]
Thank you very much, but you can also tell me if it's not difficult... Is it possible to somehow use the actual images of the elements (dinosaur, cactus, bird) and not a slice from the overall picture?

**Comment by hauph** [comment]
I assume yes, you can use several images rather than 1 big image sprite.
However you will need to modify the code a bit, for example:

<img width="1275" alt="image" src="https://github.com/user-attachments/assets/182f2aa0-6446-4416-8319-72a98fb5377d">

- In the screenshot, if you use an image of a specific element, you don't need to use `cropRect`. I am not 100% sure if it works though

**Comment by root9464** [comment]
Oh my God! thank you very much!! You've been incredibly helpful to me! I am developing a dapp application in which I needed a similar game. You've been incredibly helpful to me. Thank you very much.

**Comment by hauph** [comment]
NP. I am happy to share :+1:
